### GET request with a header
GET http://localhost:3001/api/notes
Accept: application/json

### GET request with parameter
GET http://localhost:3001/api/notes/2
Accept: application/json

### Delete request with parametr
DELETE http://localhost:3001/api/notes/4
Accept: application/json

###
POST http://localhost:3001/api/notes/
content-type: application/json

{
  "content": "sample",
  "important": true
}